version: '2.3'
services:
  tensorflow:
    # image: tensorflow/tensorflow:2.0.0rc0-gpu-py3
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - 8889:8888
    volumes:
      - ./:/workspace/Github
    runtime: nvidia
