version: '2.3'
services:
  tensorflow-meguru:
    build: .
    volumes:
      - .:/workspace
    ports:
      - 8788:8888
    runtime: nvidia
    tty: true
    command: /bin/bash
    environment:
      - CUDA_VISIBLE_DEVICES
